#!/usr/bin/env node
/**
 * embed-fonts.mjs — DSH Claude font pipeline.
 *
 * Downloads the latin subsets of the Claude-theme open-source faces from
 * Google Fonts and emits packages/client/ui-theme/src/styles/fonts.css with
 * base64 data-URL @font-face rules. Data URLs keep the theme sheet pipeline
 * (?inline imports in ui-theme/src/client/styles.ts) fully self-contained —
 * no runtime asset resolution needed.
 *
 * Faces (all SIL OFL): Cormorant Garamond (display serif, Copernicus stand-in),
 * Inter (body sans, StyreneB stand-in), JetBrains Mono (code).
 *
 * Usage: node scripts/embed-fonts.mjs
 */
import { writeFile } from 'node:fs/promises'
import path from 'node:path'

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600' +
  '&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap'
const OUT = path.resolve(
  import.meta.dirname,
  '../packages/client/ui-theme/src/styles/fonts.css',
)

const response = await fetch(CSS_URL, { headers: { 'User-Agent': UA } })
if (!response.ok) throw new Error(`fonts css fetch failed: ${response.status}`)
const css = await response.text()

// Split "/* subset */ @font-face { ... }" chunks, keep latin only (covers pt-BR).
const chunks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
const latin = chunks.filter(([, subset]) => subset === 'latin').map(([, , face]) => face)
if (latin.length === 0) throw new Error('no latin @font-face blocks found')

const faces = await Promise.all(latin.map(async (face) => {
  const urlMatch = face.match(/url\((https:[^)]+\.woff2)\)/)
  if (!urlMatch) throw new Error('face without woff2 url: ' + face)
  const font = await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })
  if (!font.ok) throw new Error(`woff fetch failed: ${font.status} ${urlMatch[1]}`)
  const b64 = Buffer.from(await font.arrayBuffer()).toString('base64')
  return face.replace(
    /src:\s*url\([^)]+\)\s*format\('woff2'\);/,
    `src: url(data:font/woff2;base64,${b64}) format('woff2');`,
  )
}))

const header =
  '/* Generated by scripts/embed-fonts.mjs — do not edit by hand.\n' +
  ' * Claude-theme faces (SIL OFL, latin subset): Cormorant Garamond = display' +
  ' serif (Copernicus stand-in), Inter = body sans (StyreneB stand-in),' +
  ' JetBrains Mono = code. Re-run the script to refresh. */\n\n'
await writeFile(OUT, header + faces.join('\n\n') + '\n', 'utf8')
console.log(`wrote ${OUT} with ${faces.length} embedded faces`)
