/** `sidebar` namespace dictionaries: shell controls (brand row, New Session, fold toggle, nav modals, profile foot). */

/**
 * The sidebar namespace dictionary (the key-set source of truth).
 */
export const en = {
  'session.new': 'New',
  'session.new.label': 'New session',
  'toggle.open': 'Open sidebar',
  'toggle.collapse': 'Collapse sidebar',
  'nav.label': 'Navigation',
  'nav.projects': 'Projects',
  'nav.artifacts': 'Artifacts',
  'nav.customize': 'Personalize',
  'nav.soon': 'Coming soon',
  'close': 'Close',
  'profile.settings': 'Settings',
  'profile.language': 'Language',
  'profile.help': 'Get help',
  'profile.search': 'Search conversations',
  'design.label': 'Design',
  'projects.modal.title': 'Projects',
  'projects.empty': 'No projects yet',
  'projects.new': 'New project',
  'projects.creating': 'Creating…',
  'projects.openFolder': 'Open folder',
  'projects.error': 'Could not create the project',
  'projects.footer': 'Files in the project folder are visible to the agent; a root AGENTS.md is injected as context automatically.',
  'artifacts.modal.title': 'Artifacts',
  'artifacts.empty': 'Files generated by Design will appear here.',
} satisfies Record<string, string>

/**
 * The pt-BR dictionary. Deliberate exception to the English-first sweep: the
 * reference chrome the fork mirrors carries these labels (Projetos / Novo),
 * so the pt locale keeps them as the visible shell.
 */
export const pt = {
  'session.new': 'Novo',
  'session.new.label': 'Nova sessão',
  'toggle.open': 'Abrir barra lateral',
  'toggle.collapse': 'Recolher barra lateral',
  'nav.label': 'Navegação',
  'nav.projects': 'Projetos',
  'nav.artifacts': 'Artefatos',
  'nav.customize': 'Personalizar',
  'nav.soon': 'Em breve',
  'close': 'Fechar',
  'profile.settings': 'Configurações',
  'profile.language': 'Idioma',
  'profile.help': 'Receber ajuda',
  'profile.search': 'Buscar conversas',
  'design.label': 'Design',
  'projects.modal.title': 'Projetos',
  'projects.empty': 'Nenhum projeto ainda',
  'projects.new': 'Novo projeto',
  'projects.creating': 'Criando…',
  'projects.openFolder': 'Abrir pasta',
  'projects.error': 'Não foi possível criar o projeto',
  'projects.footer': 'Os arquivos da pasta do projeto ficam visíveis ao agente; um AGENTS.md na raiz é injetado automaticamente.',
  'artifacts.modal.title': 'Artefatos',
  'artifacts.empty': 'Os arquivos gerados pelo Design aparecerão aqui.',
} satisfies Record<SidebarKey, string>

/** The sidebar namespace key union. */
export type SidebarKey = keyof typeof en
